# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# trigger set
trigger: none
#trigger:
#- master

pool:
  name: 'devopsdemo'

variables:
- group: azure_subscription
- group: azure_build
- name: buildConfiguration
  value: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'apiapp.test/apiapptest.csproj'
    testRunTitle: 'Test run'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'apiapp/apiapp.csproj'
    arguments: '-c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/app'
    modifyOutputPath: false

